"""empty message

Revision ID: 9225d44e394f
Revises: e5d8b877896d
Create Date: 2020-05-02 14:29:31.578889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9225d44e394f'
down_revision = 'e5d8b877896d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('idEvento', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.Column('Siglas', sa.String(length=30), nullable=False),
    sa.Column('Decripcion', sa.String(length=500), nullable=False),
    sa.Column('Duracion', sa.String(length=50), nullable=False),
    sa.Column('Cupo', sa.Integer(), nullable=False),
    sa.Column('Costo', sa.Integer(), nullable=False),
    sa.Column('Lugar', sa.String(length=100), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('imagen', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('idEvento')
    )
    op.create_table('boleto',
    sa.Column('folio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('idEvento', sa.Integer(), nullable=True),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('Asiento', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['idEvento'], ['evento.idEvento'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('folio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boleto')
    op.drop_table('evento')
    # ### end Alembic commands ###
