"""empty message

Revision ID: 1f2d15c38930
Revises: 413e93d344e3
Create Date: 2020-05-27 14:26:12.581881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2d15c38930'
down_revision = '413e93d344e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('asiento', sa.String(length=100), nullable=True))
    op.drop_column('boleto', 'Asiento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('Asiento', sa.INTEGER(), nullable=False))
    op.drop_column('boleto', 'asiento')
    # ### end Alembic commands ###
