"""empty message

Revision ID: 29856c5db00a
Revises: b157fc389166
Create Date: 2020-05-03 22:26:22.639395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29856c5db00a'
down_revision = 'b157fc389166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('edad', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('empresa', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('nombreCompleto', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('residencia', sa.String(length=70), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'residencia')
    op.drop_column('user', 'nombreCompleto')
    op.drop_column('user', 'empresa')
    op.drop_column('user', 'edad')
    # ### end Alembic commands ###
