"""empty message

Revision ID: 37a345d50b60
Revises: b32346836483
Create Date: 2020-05-05 07:33:07.308448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a345d50b60'
down_revision = 'b32346836483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boleto', 'Asiento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('Asiento', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
