"""empty message

Revision ID: 37ef5f76f9af
Revises: 1f2d15c38930
Create Date: 2020-05-27 22:07:27.830538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ef5f76f9af'
down_revision = '1f2d15c38930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('asiento', sa.String(length=100), nullable=True))
    op.drop_column('boleto', 'Asiento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('Asiento', sa.INTEGER(), nullable=False))
    op.drop_column('boleto', 'asiento')
    # ### end Alembic commands ###
