"""empty message

Revision ID: 413e93d344e3
Revises: a50a541c6064
Create Date: 2020-05-27 14:20:07.801509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413e93d344e3'
down_revision = 'a50a541c6064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('asiento', sa.String(length=100), nullable=True))
    op.drop_column('boleto', 'Asiento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('Asiento', sa.INTEGER(), nullable=False))
    op.drop_column('boleto', 'asiento')
    # ### end Alembic commands ###
