"""empty message

Revision ID: 473907c7cd56
Revises: 37ef5f76f9af
Create Date: 2020-05-27 22:09:12.157147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473907c7cd56'
down_revision = '37ef5f76f9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boleto', 'Asiento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('Asiento', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
