"""empty message

Revision ID: 4893874fd3a5
Revises: 473907c7cd56
Create Date: 2020-06-08 11:33:07.524793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4893874fd3a5'
down_revision = '473907c7cd56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boleto') as batch_op:
        batch_op.drop_column('Asiento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('Asiento', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
