"""empty message

Revision ID: 558a538be038
Revises: 29856c5db00a
Create Date: 2020-05-05 07:25:15.131522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558a538be038'
down_revision = '29856c5db00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('cantidad', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boleto', 'cantidad')
    # ### end Alembic commands ###
