"""empty message

Revision ID: a50a541c6064
Revises: 37a345d50b60
Create Date: 2020-05-05 07:34:10.214246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50a541c6064'
down_revision = '37a345d50b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('asiento', sa.String(length=100), nullable=True))
    op.drop_column('boleto', 'Asiento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('Asiento', sa.INTEGER(), nullable=False))
    op.drop_column('boleto', 'asiento')
    # ### end Alembic commands ###
