"""empty message

Revision ID: b157fc389166
Revises: 6e7ea497e449
Create Date: 2020-05-03 17:37:13.960529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b157fc389166'
down_revision = '6e7ea497e449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('numTelefono', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'numTelefono')
    # ### end Alembic commands ###
