"""empty message

Revision ID: b32346836483
Revises: 558a538be038
Create Date: 2020-05-05 07:30:36.672795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32346836483'
down_revision = '558a538be038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('asiento', sa.String(length=100), nullable=False))
    op.drop_column('boleto', 'Asiento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boleto', sa.Column('Asiento', sa.INTEGER(), nullable=False))
    op.drop_column('boleto', 'asiento')
    # ### end Alembic commands ###
